name: Check Links

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  check-links:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v5

      - uses: lycheeverse/lychee-action@v2
        id: lychee
        continue-on-error: true
        with:
          args: ". --exclude-path '.*/_.*' --exclude-path '.*/i18n/.*'"
          fail: true
          lycheeVersion: v0.22.0

      - uses: lycheeverse/lychee-action@v2
        id: lychee_markets
        continue-on-error: true
        with:
          args: "./_markets/ --exclude '^file://.*'"
          fail: true
          lycheeVersion: v0.22.0

      - uses: lycheeverse/lychee-action@v2
        id: lychee_i18n
        continue-on-error: true
        with:
          args: "./i18n/ --exclude '^file://.*'"
          fail: true
          lycheeVersion: v0.22.0

      - name: Check if any step failed
        if: steps.lychee.outcome == 'failure' || steps.lychee_markets.outcome == 'failure' || steps.lychee_i18n.outcome == 'failure'
        run: exit 1
